name: Go run tests on gateway before push/pull on main
on:
  push:
    branches:
      - main
    paths:
      - backend/gateway/**
  pull_request:
    branches:
      - main
    paths:
      - backend/gateway/**
jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define your environment variables here
      PORT: 8080
      TESTPORT: 0.0.0.0:8002
    defaults:
      run:
        working-directory: backend/gateway
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Build and Run Tests
        run: go test ./... -v
